export const Infocards = [
  {
    info: "Test",
    desc: "Employee",
  },
  {
    info: "metch information technology ",
    desc: "Customer",
  },
  {
    info: "Partner",
    desc: "User Role",
  },
  {
    info: "31/12/2023",
    desc: "Audit Period End Date",
  },
];
export const Independences = [
  {
    id: "1",
    name: "Do you read the rules of independence and its interpretation according to the requirements of laws and regulations related to the profession and the professional standards by Saudi Organization for chartered and Professional Accountant and other related laws?",
    yes: 1,
    no: 0,
    notes: "No Comment",
  },
  {
    id: "2",
    name: "Have you reviewed the names of founders, board members, executives and partners for the client to see if there are operations or relationships prejudice the requirements of independence?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "3",
    name: "Do you have a relative relation with one of founders, board members or client's executives?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "4",
    name: "Are you one of the entity’s co-founders?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "5",
    name: "Are you member of the board of directors?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "6",
    name: "Do you provide a consultancy services to the client?",
    yes: 1,
    no: 0,
    notes: "No Comment",
  },
  {
    id: "7",
    name: "Do you own significant equity shares of the client?",
    yes: 1,
    no: 0,
    notes: "No Comment",
  },
  {
    id: "8",
    name: "Are you a partner for one of key client’s staff?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "9",
    name: "Are you a business partner for one of client senior partners?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "10",
    name: "Are you a business partner for the client?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "11",
    name: "Are you an endowment’s trustee where the client has a share?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "12",
    name: "Are you an inheritance’s trustee where the client has a share?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "13",
    name: "Do you have a loan from the client?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "14",
    name: "Do you have a loan from one of key client staff?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "15",
    name: "Do you have a loan from a member of board of director?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "16",
    name: "Do you have a loan from one of client’s senior partners?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "17",
    name: "Do you own a similar business?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
  {
    id: "18",
    name: "Are you a member of board of directors for an entity that have a similar business?",
    yes: 0,
    no: 1,
    notes: "No Comment",
  },
];
